### ISSUE TITLE
npm install report error

### ISSUE THREAD

**Issue by NetScotte** [isanxia/mercury-client#1]
11 warnings and 3 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/net/HBuilderProjects/resource/mercury-client/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/12.12.0/bin/node" "/Users/net/HBuilderProjects/resource/mercury-client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/net/HBuilderProjects/resource/mercury-client/node_modules/node-sass
gyp ERR! node -v v12.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.10.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.10.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/net/.npm/_logs/2020-11-21T08_48_48_306Z-debug.log

**Comment by Curricane** [comment]
我遇到了和你类似的问题，需要用cnpm i 来安装才行
我的环境：
  macos 11 bigsur 
  node.js版本:v14.15.1
执行步骤：
  // 设置 淘宝镜像源
  npm config set registry https://registry.npm.taobao.org 
  // 安装 淘宝镜像源和cnpm
  npm install -g cnpm --registry=https://registry.npm.taobao.org
  // 在项目目下安装依赖
  sudo cnpm i
